import { Parcel, ReturnRecord } from './types';

export const INITIAL_PARCELS: Parcel[] = [
  {
    id: 'p-1',
    trackingNumber: 'SPXPH0394829104',
    platform: 'Shopee',
    courier: 'SPX Express',
    customer: 'Maria Santos',
    phone: '+63 917 *** 4821',
    destination: 'Quezon City, Metro Manila',
    amount: '₱1,250.00',
    rawAmount: 1250,
    status: 'Dispatched',
    statusColor: '#3B82F6',
    dispatchedAt: 'Today, 09:30 AM',
    dateISO: '2026-10-05T09:30:00',
    items: '2x Wireless Earbuds, 1x Silicone Case'
  },
  {
    id: 'p-2',
    trackingNumber: 'LEX-PH-82049102',
    platform: 'Lazada',
    courier: 'Lazada Express',
    customer: 'Juan Dela Cruz',
    phone: '+63 928 *** 9934',
    destination: 'Cebu City, Central Visayas',
    amount: '₱3,420.00',
    rawAmount: 3420,
    status: 'In Transit',
    statusColor: '#8B5CF6',
    dispatchedAt: 'Yesterday, 04:15 PM',
    dateISO: '2026-10-04T16:15:00',
    items: '1x Mechanical Keyboard (RGB Brown Switch)'
  },
  {
    id: 'p-3',
    trackingNumber: 'JT6301948201',
    platform: 'TikTok Shop',
    courier: 'J&T Express',
    customer: 'Elena Garcia',
    phone: '+63 905 *** 1276',
    destination: 'Davao City, Davao del Sur',
    amount: '₱890.00',
    rawAmount: 890,
    status: 'Delivered',
    statusColor: '#10B981',
    dispatchedAt: '2 days ago, 11:20 AM',
    dateISO: '2026-10-03T11:20:00',
    items: '3x Premium Cotton Oversized Tees'
  },
  {
    id: 'p-4',
    trackingNumber: 'LBC88301928',
    platform: 'Shopee',
    courier: 'Flash Express',
    customer: 'Roberto Tan',
    phone: '+63 918 *** 6712',
    destination: 'Pasig City, Metro Manila',
    amount: '₱2,100.00',
    rawAmount: 2100,
    status: 'Return Logged',
    statusColor: '#EF4444',
    dispatchedAt: '3 days ago, 02:40 PM',
    dateISO: '2026-10-02T14:40:00',
    items: '1x Ergonomic Desk Lamp'
  },
  {
    id: 'p-5',
    trackingNumber: 'SPXPH994820194',
    platform: 'Shopee',
    courier: 'SPX Express',
    customer: 'Chloe Mendoza',
    phone: '+63 922 *** 8810',
    destination: 'Taguig City, BGC',
    amount: '₱1,780.00',
    rawAmount: 1780,
    status: 'Dispatched',
    statusColor: '#3B82F6',
    dispatchedAt: 'Today, 11:05 AM',
    dateISO: '2026-10-05T11:05:00',
    items: '1x Portable Bluetooth Speaker'
  },
  {
    id: 'p-6',
    trackingNumber: 'LEX-PH-19028471',
    platform: 'Lazada',
    courier: 'Lazada Express',
    customer: 'Mark Anthony Ramos',
    phone: '+63 919 *** 5521',
    destination: 'Makati City, Metro Manila',
    amount: '₱4,650.00',
    rawAmount: 4650,
    status: 'In Transit',
    statusColor: '#8B5CF6',
    dispatchedAt: 'Yesterday, 02:00 PM',
    dateISO: '2026-10-04T14:00:00',
    items: '1x 24-inch IPS Monitor Mount'
  },
  {
    id: 'p-7',
    trackingNumber: 'JT9928174621',
    platform: 'TikTok Shop',
    courier: 'J&T Express',
    customer: 'Bea Alonzo-Perez',
    phone: '+63 915 *** 3189',
    destination: 'Iloilo City, Western Visayas',
    amount: '₱1,490.00',
    rawAmount: 1490,
    status: 'Delivered',
    statusColor: '#10B981',
    dispatchedAt: '4 days ago, 10:15 AM',
    dateISO: '2026-10-01T10:15:00',
    items: '2x Skincare Glow Serum Set'
  },
  {
    id: 'p-8',
    trackingNumber: 'SPXPH773019823',
    platform: 'Shopee',
    courier: 'SPX Express',
    customer: 'Daniel Padilla-Cruz',
    phone: '+63 917 *** 2209',
    destination: 'Antipolo, Rizal',
    amount: '₱3,150.00',
    rawAmount: 3150,
    status: 'Delivered',
    statusColor: '#10B981',
    dispatchedAt: 'Sep 28, 03:20 PM',
    dateISO: '2026-09-28T15:20:00',
    items: '1x Android Car Head Unit'
  },
  {
    id: 'p-9',
    trackingNumber: 'JT5520194821',
    platform: 'TikTok Shop',
    courier: 'J&T Express',
    customer: 'Janine Berdin',
    phone: '+63 908 *** 7711',
    destination: 'Cagayan de Oro, Misamis Oriental',
    amount: '₱760.00',
    rawAmount: 760,
    status: 'Delivered',
    statusColor: '#10B981',
    dispatchedAt: 'Sep 22, 08:45 AM',
    dateISO: '2026-09-22T08:45:00',
    items: '3x Lip Tint Set & Velvet Powder'
  },
  {
    id: 'p-10',
    trackingNumber: 'LEX-PH-44019283',
    platform: 'Lazada',
    courier: 'Lazada Express',
    customer: 'Alvin Lim',
    phone: '+63 920 *** 4410',
    destination: 'Baguio City, Benguet',
    amount: '₱2,890.00',
    rawAmount: 2890,
    status: 'Delivered',
    statusColor: '#10B981',
    dispatchedAt: 'Sep 12, 01:10 PM',
    dateISO: '2026-09-12T13:10:00',
    items: '1x Espresso Hand Grinder Pro'
  }
];

export const INITIAL_RETURNS: ReturnRecord[] = [
  {
    id: 'ret-1',
    trackingNumber: 'LBC88301928',
    platform: 'Shopee',
    courier: 'Flash Express',
    customer: 'Roberto Tan',
    reason: 'RTS: Delivery Failed / Customer Unreachable',
    condition: 'Intact (Resellable)',
    refundStatus: 'Pending Inspection',
    loggedAt: 'Oct 04, 2026 • 03:15 PM',
    refundAmount: '₱2,100.00',
    notes: 'Rider attempted 3x deliveries. Parcel intact with original tamper seal intact.'
  },
  {
    id: 'ret-2',
    trackingNumber: 'SPXPH881923019',
    platform: 'Shopee',
    courier: 'SPX Express',
    customer: 'Kenneth David',
    reason: 'Wrong Item Model Received',
    condition: 'Damaged Packaging',
    refundStatus: 'Approved for Refund',
    loggedAt: 'Oct 03, 2026 • 11:40 AM',
    refundAmount: '₱1,850.00',
    notes: 'Outer box opened by customer, unit unpowered and accessory pack complete.'
  },
  {
    id: 'ret-3',
    trackingNumber: 'JT7738192019',
    platform: 'TikTok Shop',
    courier: 'J&T Express',
    customer: 'Aileen Reyes',
    reason: 'Damaged during Courier Transit',
    condition: 'Item Damaged',
    refundStatus: 'Disputed with Platform',
    loggedAt: 'Oct 02, 2026 • 04:55 PM',
    refundAmount: '₱3,100.00',
    notes: 'Waybill crushed. Filing courier compensation claim against J&T Express hub.'
  }
];

export const INITIAL_PRODUCTS: import('./types').Product[] = [
  {
    id: 'prod-1',
    name: 'Pro Wireless ANC Earbuds (BT 5.4)',
    category: 'Electronics',
    price: '₱1,250.00',
    rawPrice: 1250,
    stock: 48,
    description: 'Active Noise Cancelling earbuds with deep bass, low latency gaming mode, and 36hr battery life.',
    platforms: ['Shopee', 'Lazada', 'TikTok Shop'],
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    reviewsCount: 312
  },
  {
    id: 'prod-2',
    name: 'RGB Hot-Swappable Mechanical Keyboard',
    category: 'Electronics',
    price: '₱3,420.00',
    rawPrice: 3420,
    stock: 19,
    description: '75% Layout wireless tri-mode mechanical keyboard with pre-lubed Brown Switches and custom PBT keycaps.',
    platforms: ['Lazada', 'Shopee'],
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    reviewsCount: 184
  },
  {
    id: 'prod-3',
    name: 'Heavy Duty 24"-34" Gas Spring Monitor Mount',
    category: 'Accessories',
    price: '₱4,650.00',
    rawPrice: 4650,
    stock: 14,
    description: 'Aircraft-grade aluminum single monitor arm with integrated cable management channels and clamp base.',
    platforms: ['Lazada'],
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    reviewsCount: 96
  },
  {
    id: 'prod-4',
    name: 'Ergonomic LED Desk Lamp with Wireless Qi Charger',
    category: 'Home & Living',
    price: '₱2,100.00',
    rawPrice: 2100,
    stock: 32,
    description: 'Multi-angle dimmable eye-caring task light with 5 color temperatures, timer, and 15W phone charging pad.',
    platforms: ['Shopee', 'TikTok Shop'],
    image: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?w=500&auto=format&fit=crop&q=60',
    rating: 4.7,
    reviewsCount: 142
  },
  {
    id: 'prod-5',
    name: 'Premium 240GSM Heavyweight Oversized Tee (3-Pack)',
    category: 'Apparel',
    price: '₱890.00',
    rawPrice: 890,
    stock: 65,
    description: 'Pre-shrunk 100% combed cotton streetwear drop-shoulder tees. Breathable and fade-resistant.',
    platforms: ['TikTok Shop', 'Shopee'],
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&auto=format&fit=crop&q=60',
    rating: 4.9,
    reviewsCount: 420
  },
  {
    id: 'prod-6',
    name: 'IPX7 Waterproof Rugged Outdoor Bluetooth Speaker',
    category: 'Electronics',
    price: '₱1,780.00',
    rawPrice: 1780,
    stock: 27,
    description: '20W 360-degree stereo sound with punchy bass radiators, built-in mic, and carabiner clip.',
    platforms: ['Shopee', 'TikTok Shop'],
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format&fit=crop&q=60',
    rating: 4.8,
    reviewsCount: 168
  }
];

export const INITIAL_CHAT_MESSAGES: import('./types').ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'customer',
    senderName: 'Maria Santos',
    text: 'Good morning! Could you check if my order #SPXPH0394829104 was dispatched today?',
    timestamp: 'Today, 09:45 AM',
    trackingNumber: 'SPXPH0394829104'
  },
  {
    id: 'msg-2',
    sender: 'admin',
    senderName: 'Admin (Nolan Caparros)',
    text: 'Hello Maria! Yes, your parcel was processed and dispatched at 09:30 AM via SPX Express. It is currently headed to the Quezon City Sort Center.',
    timestamp: 'Today, 09:47 AM',
    trackingNumber: 'SPXPH0394829104'
  },
  {
    id: 'msg-3',
    sender: 'customer',
    senderName: 'Maria Santos',
    text: 'Awesome, thank you so much! Also, do you have more stock for the RGB mechanical keyboard in brown switch?',
    timestamp: 'Today, 10:12 AM'
  },
  {
    id: 'msg-4',
    sender: 'admin',
    senderName: 'Admin (Nolan Caparros)',
    text: 'Yes! We have 19 units left in the central hub. You can place an order directly from the Store tab anytime!',
    timestamp: 'Today, 10:15 AM'
  }
];

export const INITIAL_USERS: import('./types').UserRecord[] = [
  {
    uid: 'usr-admin-01',
    email: 'nolancaparros.draft@gmail.com',
    displayName: 'Nolan Caparros',
    role: 'admin',
    registeredAt: 'Oct 01, 2026',
    dpaConsent: true,
  },
  {
    uid: 'usr-staff-01',
    email: 'staff.marcos@gmail.com',
    displayName: 'Marcos Dela Cruz',
    role: 'staff',
    registeredAt: 'Oct 02, 2026',
    dpaConsent: true,
  },
  {
    uid: 'usr-cust-01',
    email: 'maria.santos@gmail.com',
    displayName: 'Maria Santos',
    role: 'customer',
    registeredAt: 'Oct 03, 2026',
    dpaConsent: true,
  },
  {
    uid: 'usr-cust-02',
    email: 'new.user@gmail.com',
    displayName: 'Alex Reyes (New Sign-In)',
    role: 'customer',
    registeredAt: 'Today, 08:30 AM',
    dpaConsent: true,
  },
];
